function selectedLang(){
  if (localStorage.getItem("lang")){
    return localStorage.getItem("lang")
  } else {
    localStorage.setItem('lang', 'EN')
    return 'EN'
  }
}

const content = {
  EN: {
    // Main menu
    myDashboard: "Home",
    myBinaryTree: "Organization",
    myReferrerTree: "Referrers tree",
    myConfiguration: "Settings",
    myProfile: "Account",
    myPlans: "Packs",
    myInvoices: "Purchases",
    myTransactions: "History",
    myWithdrew: "Pay Out",
    myHistory: "Stats",
    myProducts: "Products",
    myMarketplace: "Marketplace",
    //
    title1: "Dashboard",
    subtitle1: "Welcome to your backoffice",
    linkToRefer: "My referral link",
    activeLeg: "Active Leg",
    rightLeg: "Right",
    leftLeg: "Left",
    availableBalance: "Available in Wallet",
    monthlyProfit: "Monthly Earnings",
    cryptoCurrency: "Cryptocurrency",
    cryptoPrice: "Price",
    cryptoChange: "24h % Change",
    cryptoVolume: "24h Volume (USD)",
    cryptoPrice: "Price",
    cryptoSuply: "Available",
    market: "Market",
    lastUsers: "Last Users",
    ago: "Ago",
    registered: "Registered",
    title2: "Buy trading pack",
    subtitle2: "Get your plan and start earning Today!",
    products: "Products",
    planBuy: "Buy Plans",
    buyToday: "Buy your plan today and start receiving benefits",
    days: "Days",
    dailyWithdraw: "Monday to Friday withdrawals",
    dailyPayouts: "Monday to sunday payouts (ROI)",
    mineTime: "Mining Time",
    payDays: "Pay days M-F",
    buyNow: "Buy Now",
    title3: "Binary Tree",
    subtitle3: "Revise your organization",
    filterUser: "Filter by User",
    refresh: "Refresh",
    binaryVolume: "Binary Volume",
    leftPoints: "Left Points",
    rightPoints: "Right Points",
    colorCode: "Color Code",
    noPlan: "No Plan",
    bronze: "Bronze",
    silver: "Silver",
    gold: "Gold",
    ruby: "Ruby",
    planType1: "Plan Basic",
    planType2: "Plan Advanced",
    planType3: "Plan Pro",
    title4: "My Profile",
    subtitle4: "Edit Profile",
    profile: "Profile",
    configuration: "Configuration",
    username: "Username",
    changeAvatar: "Change avatar",
    name: "Name",
    lastName: "Last Name",
    email: "Email",
    affiliated: "Affiliated",
    passwordChange: "Change Password",
    newPassword: "New Password",
    newPasswordConfirm: "Confirm New Password",
    changePassword: "Change password",
    title5: "My Subscriptions",
    subtitle5: "Review my Subscriptions Satus",
    subLists: "Subscriptions List",
    planName: "Plan Name",
    remainingDays: "Remaining Days",
    value: "Value",
    status: "Status",
    details: "Details",
    timeLine: "Time Line",
    title6: "My Invoices",
    subtitle6: "Review my Invoices",
    invoiceList: "Invoice List",
    currency: "Currency",
    created: "Created",
    title7: "Withdrawals",
    subtitle7: "Request Withdraw.",
    transactions: "Transactions",
    withdrawalRequest: "Request Withdraw.",
    balanceIn: "Balance in",
    withdrawForm: "Withdraw form",
    amountToWithdraw: "Amount to Withdraw",
    minimumWithdraw: "Minimum Withdraw",
    whithdrawType: "Withdraw Amount",
    destinyWallet: "Recepient Wallet",
    sellBalance: "Balance Transfer",
    notes: "Notes",
    acceptTerms: "Accept Terms and Conditions",
    request: "Request",
    subtitle7: "History Reports.",
    history: "History",
    stats: "Reports",
    investmentPlans: "Investments Plans",
    binaryBonus: "Bynary Bonus",
    unilevelBonus: "Direct Bonus",
    purchases: "Purchaces",
    whitdrew: "Withdrawals",
    historyText1: "Here you could review your investment payments.",
    historyText2: "Your bonuses for binary commisions",
    historyText3: "Review your unilevel bonus.",
    historyText4: "Purchases History.",
    historyText5: "Witdrawal History.",
    type: "Type",
    referer: "Referred by",
    wallet: "Wallet",
    comission: "Comission",
    close: "Close",
    repurchase: "REPURCHASE OK",
    qty: "Quantity",
    fees: "fees",
    total: "Total",
    notEnoughBalance: "Insuficient Funds",
    confirmPurchase: "Confirm Purchase",
    proccesing: "Proccesing",
    repurchaseSuccessText:
      "Repurchase approved ok!. This is your new balance",
    selectPayment: "Select payment method",
    purchaseModalText1:
      "When click on confirm, the price will be deducted from your actual balance",
    planValue: "Plan Price",
    plan: "Plan",
    updated: "Updated",
    investmentPlanFilter: "Investment Plan Filter",
    txid:"TXID",
    monthly: "Monthly",
    title8: 'Reports',
    title9: 'Referrers tree',
    subTitle9: 'Referrers tree',
    account: 'Account',
    referrers: 'referrers',
    residualBonus: 'Residual bonus'
  },
  
  ES: {
    // Main menu
    myDashboard: "Inicio",
    myBinaryTree: "Organizacion",
    myReferrerTree: "Referidos",
    myConfiguration: "Opciones",
    myProfile: "Cuenta",
    myPlans: "Paquetes",
    myInvoices: "Compras",
    myTransactions: "Historial",
    myWithdrew: "Transferir",
    myHistory: "Estadisticas",
    myProducts: "Paquetes",
    myMarketplace: "Paquetes de trade",
    //
    title1: "Inicio",
    subtitle1: "Bienvenido a tu oficina",
    linkToRefer: "Mi link para referir",
    activeLeg: "Pierna activa",
    rightLeg: "Derecha",
    leftLeg: "Izquierda",
    availableBalance: "Disponible en billetera",
    monthlyProfit: "Ganancias por mes",
    cryptoCurrency: "Crypto moneda",
    cryptoPrice: "Precio",
    cryptoChange: "24h % Cambio",
    cryptoVolume: "24h Volumen (USD)",
    cryptoPrice: "Precio",
    cryptoSuply: "Disponible",
    market: "Mercado",
    lastUsers: "Ultimos usuarios",
    ago: "Hace",
    registered: "se ha registrado!",
    title2: "Plan de trading",
    subtitle2: "Adquiere tu plan hoy y comienza a generar ganancias.",
    products: "Productos",
    planBuy: "Compra de planes",
    buyToday: "Compra tu plan hoy y comienza a generar beneficios.",
    days: "Dias",
    dailyWithdraw: "Retiros Lunes a Viernes",
    dailyPayouts: "Pagos lunes a domingo (ROI)",
    mineTime: "Tiempo de mineria",
    payDays: "pago L-V",
    buyNow: "Comprar ahora",
    title3: "Arbol binario",
    subtitle3: "Revisa tu organización.",
    filterUser: "Filtrar usuario",
    refresh: "Refrescar",
    binaryVolume: "Volumen binario",
    leftPoints: "Puntos izquierda",
    rightPoints: "Puntos derecha",
    colorCode: "Codigo de color",
    noPlan: "Sin plan",
    bronze: "Bronce",
    silver: "Plata",
    gold: "Dorado",
    ruby: "Ruby",
    planType1: "Plan Basic",
    planType2: "Plan Advanced",
    planType3: "Plan Pro",
    title4: "Mi perfil",
    subtitle4: "Editar perfil",
    profile: "Perfil",
    configuration: "Configuracion",
    username: "Usuario",
    changeAvatar: "Cambiar avatar",
    name: "Nombre",
    lastName: "Apellido",
    email: "Email",
    affiliated: "Afiliado",
    passwordChange: "Cambio de password",
    newPassword: "Nuevo password",
    newPasswordConfirm: "Confirma tu nuevo password",
    changePassword: "Cambiar password",
    title5: "Mis subscripciones",
    subtitle5: "Revisa el estado de tus subscripciones.",
    subLists: "Listado de subscripciones",
    planName: "Nombre de plan",
    remainingDays: "Dias restantes",
    value: "Valor",
    status: "Estado",
    details: "Detalles",
    timeLine: "Linea de tiempo",
    title6: "Mis facturas",
    subtitle6: "Revisa tu facturación.",
    invoiceList: "Listado de facturas",
    currency: "Moneda",
    created: "Creación",
    title7: "Retiros",
    subtitle7: "Solicitar retiro.",
    transactions: "Transacciones",
    withdrawalRequest: "Solicitar retiro",
    balanceIn: "Balance en",
    withdrawForm: "Formulario de retiro",
    amountToWithdraw: "Monto a retirar en",
    minimumWithdraw: "El retiro debe ser minimo de",
    whithdrawType: "Monto de retiro",
    destinyWallet: "Billetera de destino",
    sellBalance: "Translado de saldo",
    notes: "Notas",
    acceptTerms: "Aceptar terminos y condiciones",
    request: "Solicitar",
    subtitle7: "Estadisticos historicos.",
    history: "Historial",
    stats: "Estadisticos",
    investmentPlans: "Planes de inversion",
    binaryBonus: "Bono binario",
    unilevelBonus: "Bono directo",
    purchases: "Compras",
    whitdrew: "Retiros",
    historyText1: "Acá podras revisar tus pagos por inversion.",
    historyText2: "Tus bonos por comision binaria.",
    historyText3: "Revisa tus bonos unilevel.",
    historyText4: "Historial de tus compras.",
    historyText5: "Historial de tus retiros.",
    type: "Tipo",
    referer: "Referido",
    wallet: "Wallet",
    comission: "Comisión",
    close: "Cerrar",
    repurchase: "RECOMPRA EXITOSA",
    qty: "Cantidad",
    fees: "fees",
    total: "Total",
    notEnoughBalance: "Balance insuficiente",
    confirmPurchase: "Confirmar compra",
    proccesing: "Procesando",
    repurchaseSuccessText:
      "Recompra aprobada exitosamente!. Este es tu nuevo balance",
    selectPayment: "Selecciona un metodo de pago",
    purchaseModalText1:
      "Al hacer click en confirmar el valor de tu plan será descontado de tu balance actual",
    planValue: "Valor de plan",
    plan: "Plan",
    updated: "Actualizado",
    investmentPlanFilter: "Filtro por plan de inversion",
    txid:"TXID",
    monthly: "Mensual",
    title8: 'Reportes',
    title9: 'Arbol de referidos',
    subTitle9: 'Referidos',
    account: 'Cuenta',
    referrers: 'referidos',
    residualBonus: 'Bono residual'
  }
};

module.exports = content[selectedLang()]